### ISSUE TITLE
FR: integrate with zon package manager

### ISSUE THREAD

**Issue by glyh** [kivikakk/libpcre.zig#13]
As title, here's instructions on how to use them:

https://zig.news/edyu/zig-package-manager-wtf-is-zon-558e

**Comment by kivikakk** [comment]
Pull requests gratefully accepted!

**Comment by glyh** [comment]
Looks like we can do this but users still have to link against libpcre manually which is not ideal. Related: https://github.com/ziglang/zig/issues/16172
